---
- hosts: service
  tasks:
          - name: copy Dockerfile
            copy:
                    src: ../doker/Dockerfile
                    dest: /root/Dockerfile
          - name: copy files
            copy:
                    src: ../doker/files/
                    dest: /root/files/

          - name: build image
            docker_image:
                    name: wiremock
                    build:
                            path: /root/
                    source: build
                    state: present

